SELECT 
TM.SHDES, TM.VSCODE, SP.SHDES, SN.SHDES, RIM.TYPEIND, RIM.VSCODE, TT.SHDES, ZN.SHDES,
RIM.IL01, RIM.IR01, RIM.IM01, RIM.IC01,
RIM.IL02, RIM.IR02, RIM.IM02, RIM.IC02,
RIM.IL03, RIM.IR03, RIM.IM03, RIM.IC03,
RIM.IL04, RIM.IR04, RIM.IM04, RIM.IC04,
RIM.IL05, RIM.IR05, RIM.IM05, RIM.IC05,
RIM.IL06, RIM.IR06, RIM.IM06, RIM.IC06,
RIM.IL07, RIM.IR07, RIM.IM07, RIM.IC07,
RIM.IL08, RIM.IR08, RIM.IM08, RIM.IC08,
RIM.IL09, RIM.IR09, RIM.IM09, RIM.IC09,
RIM.IL10, RIM.IR10, RIM.IM10, RIM.IC10
FROM
MPULKRIM RIM,
MPUTTTAB TT,
MPUZNTAB ZN,
MPURITAB RI,
MPULKTMM TMM,
MPUTMTAB TM,
MPUSNTAB SN,
MPUSPTAB SP
WHERE
TMM.TMCODE = TM.TMCODE 
AND TMM.VSCODE = TM.VSCODE
AND TMM.SPCODE = SP.SPCODE
AND TMM.SNCODE = SN.SNCODE
AND TMM.STATUS = 'P'
AND RI.RICODE = TMM.RICODE
AND RI.RICODE = RIM.RICODE 
AND RIM.TTCODE = TT.TTCODE
AND RIM.ZNCODE = ZN.ZNCODE;
